In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file reading and writing
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [2]:
datasets = "./datasets/datasets - crop irrigation.csv"
raw_data = pd.read_csv(datasets)
raw_data.head()

  CropType  CropDays  SoilMoisture  temperature  Humidity  Irrigation
0    Wheat        10           400           30        15           0
1    Wheat         7           200           30        32           0
2    Wheat         9           300           21        28           0
3    Wheat         3           500           40        22           0
4    Wheat         2           700           23        34           0

In [7]:
raw_data.sample(frac=1)

           CropType  CropDays  SoilMoisture  temperature  Humidity  Irrigation
300          Potato        58           136           16        68           0
497          Coffee        95           210           23        17           0
376       Sugarcane        56           339           18        69           0
27            Wheat        37           700           30        22           1
319          Potato        94           330           16        68           0
..              ...       ...           ...          ...       ...         ...
336           Pulse        16           650           30        18           1
101      Groundnuts        47           450           27        17           0
226           Paddy        10           147           26        13           0
146  Garden Flowers        50           320           18        80           0
12            Wheat        19           649           29        61           0

[501 rows x 6 columns]

In [8]:
X = raw_data.drop('Irrigation', axis="columns")
Y = raw_data['Irrigation']
X["CropType"].unique()

array(['Wheat', 'Groundnuts', 'Garden Flowers', 'Maize', 'Paddy',
       'Potato', 'Pulse', 'Sugarcane', 'Coffee'], dtype=object)

In [9]:
label_encoder = preprocessing.LabelEncoder()
X['CropType'] = label_encoder.fit_transform(X['CropType']) # encode the crop type label
X['CropType'].unique()

array([8, 2, 1, 3, 4, 5, 6, 7, 0])

In [10]:
label_encoder.fit_transform(["Paddy", "Coffee", "Groundnuts", "Maize", "Wheat", "Garden Flowers", "Potato", "Sugarcane", "Pulse"])

array([4, 0, 2, 3, 8, 1, 5, 7, 6])

In [11]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X,Y,train_size = 0.8)

In [12]:
Xtrain.shape

(400, 5)

In [14]:
Xtrain.sample(frac=1)

     CropType  CropDays  SoilMoisture  temperature  Humidity
362         7        29           186           18        79
455         0        11           456           27        16
370         7        45           129           18        70
408         7       120           189           25        50
335         6        13           329           28        29
..        ...       ...           ...          ...       ...
190         3        39           440           34        19
128         1         1           400           24        70
111         2        66           780           22        21
419         7       142           689           32        38
44          8        77           450           21        14

[400 rows x 5 columns]

In [35]:
np.savez('./processed_data/crop_data.npz', Xtrain=Xtrain, Ytrain=Ytrain, Xtest=Xtest, Ytest=Ytest)

In [40]:
data = np.load('./processed_data/crop_data.npz', allow_pickle=True)

In [42]:
Xtrain = data['Xtrain']
Ytrain = data['Ytrain']
Xtest = data['Xtest']
Ytest = data['Ytest']
Xtrain.shape

(400, 5)